<?php
$scriptList = array('js/jquery-3.1.0.min.js', 'js/carousel.js');
include('privatePHP/header.php');
?>


        <div id="main">
            <p>
                Welcome to Classic Cinema, your online store for classic film.
            </p>
            <div id="carousel">
                <!-- Content generated by JavaScript in carousel.js -->
            </div>
        </div>

<?php include("privatePHP/footer.php");?>